### ISSUE TITLE
Example scripts for Paté?

### ISSUE THREAD

**Issue by dylanHco** [gtiley/Phasing#4]
Hello, 

Thank you for creating this program. I would like to use it on my dataset which contains diploids, tetraploids and hexaploids as well as hybrids but I am struggling to get it working on the Linux machine I am using. I was wondering if you could share any of the previous/example scripts that have worked for getting Paté to run on a Linux server? This would be a great help to see an example of how its been coded before.

Also in the control file the line that starts with #Name of the reference individual that matches the header in the reference fasta file, should this just be commented out if I am running in Species mode? 

A bunch of the software is already preinstalled, if they are loaded in the template script do I need to write the paths in the control script?

Thanks for anyhelp/suggestions!
Dylan

**Comment by andycrowl** [comment]
Hey Dylan -- Happy to share some example scripts to run PATE on a Linux server! Shoot me an email (andy.crowl[a]ufl.edu) and I'll send them your way!

Andy

**Comment by gtiley** [comment]
Thanks for helping out Andy! 

@dylanHco - Andy ran PATÉ on a Linux server for some of our collaborative _Vaccinium_ research. Once you are up and running we can close the issue.

 @andycrowl - CC me on the email chain and I will write some documentation on using a Linux server for future reference.

**Comment by korjent** [comment]
Hi Andy and George,

I am in the process of getting PATE setup on our HPC, but have not been successful in getting it working. Is it possible to also get some example data and files to see if it is working.
Appreciate it a lot!

Cheers

Kor

**Comment by andycrowl** [comment]
Hey Kor --

Attaching here an example of the control file (*PATE.ctl*) and three
example submit scripts.

You need to first format your fasta files using *submit_PATE_format_refs.sh*,
then you run the pipeline's two runmodes:
1 — *submit_PATE_1_genotype.sh*
*2 — submit_PATE_2_alleles.sh*

I tried to put notes in the submit scripts to make things clear.

For the genotyping step (PATE_1), you run the command on line 39 from the
command line and leave the submit script as-is (leave everything at the
bottom commented out, this file acts as a blank template to submit your
jobs in parallel).

Then for PATE_2, you actually submit the submit script (with the command on
line 45 uncommented)

Make sure to change the submit scripts to reflect the mem-per-cpu and
ntasks that are appropriate for your HPC!



Are you planning to use the pipeline to estimate ploidy of your samples or
do you already know ploidy??

Happy to jump on a zoom call to chat through this if it's not clear or
you're still stuck!
Andy

**Comment by andycrowl** [comment]
Kor --
Can you send me an email -- andy.crowl[a]ufl.edu -- and i'll share the
example submit scripts with you?!

Andy

**Comment by gtiley** [comment]
@korjent Were you successful with your analyses? If so, I will go ahead and close the issue. I was on hiatus for a while but am starting to move PATE over to Nextflow to make things easier, maybe that will be ready later this year. I will close the issue if you were able to launch the analyses on your HPC.

**Comment by korjent** [comment]
Hi George,

No no luck yet. 
The interaction with our HPC is slightly different and not compatible with your flow.
Might try again one day when the new workflow has been established.

Kind regrds

Kor

Kor-jent van Dijk
***@***.***
(+61) 0415430512

**Comment by yjk-bertrand** [comment]
Hi Andy and George,
We are trying to set up PATE on our cluster, but we keep running into Picard related errors.
Would you be so kind and share some test input in order to debug our installation?
Thanks,
Yann

**Comment by gtiley** [comment]
Hi Yann,

Have you tried the example provided in the Dryad repo associated with the 2024 Syst Biol paper? There is a working example for the ferns provided there: https://datadryad.org/dataset/doi:10.5061/dryad.5qfttdz53

Otherwise, can you share the error from Picard and your control file?

**Comment by V-Z** [comment]
Hello,
I downloaded the [data](https://www.ebi.ac.uk/ena/browser/view/PRJNA725004), renamed the files [accordingly](https://zenodo.org/records/10117412) and tried them as `perl PATE.pl --controlFile ./PATE.ctl --runmode species --genotype consensus --template template.sh` and unfortunately failed. I wonder if You could advice me what went wrong.

For every sample I get errors like
```
Using GATK jar /afs/ics.muni.cz/software/gatk/4.1.6.0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /afs/ics.muni.cz/software/gatk/4.1.6.0/gatk-package-4.1.6.0-local.jar VariantFilt
ration -R /storage/pruhonice1-ibot/shared/hieracium/pate/test_files/genotypeOutput/UFG_393202_P004_WA01/UFG_393202_P004_WA01.ref.fasta -V /storage/pruhonice1-ibot/shared/hieracium/pate/test_files/genotypeOutput/UFG_393202_P004_WA01/UFG_393202_P004_WA
01.ab.vcf -O /storage/pruhonice1-ibot/shared/hieracium/pate/test_files/genotypeOutput/UFG_393202_P004_WA01/UFG_393202_P004_WA01.abf.vcf --filter-expression QD < 2.0 --filter-name QD_lt2 --filter-expression FS > 60.0 --filter-name FS_gt60 --filter-exp
ression MQ < 40.0 --filter-name MQ_lt40 --filter-expression ReadPosRankSum < -8.0 --filter-name ReadPosRankSum_ltm8 --filter-expression AF < 0.025 --filter-name AF_lt025 --filter-expression AF > 0.975 --filter-name AF_gt975 --filter-expression DP < 1
0 --filter-name DP_lt10
18:03:29.458 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/afs/ics.muni.cz/software/gatk/4.1.6.0/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 26, 2025 6:03:29 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
18:03:29.589 INFO  VariantFiltration - ------------------------------------------------------------
18:03:29.590 INFO  VariantFiltration - The Genome Analysis Toolkit (GATK) v4.1.6.0
18:03:29.590 INFO  VariantFiltration - For support and documentation go to https://software.broadinstitute.org/gatk/
18:03:29.590 INFO  VariantFiltration - Executing as gunnera@draba1.ibot.cas.cz on Linux v6.1.0-37-amd64 amd64
18:03:29.590 INFO  VariantFiltration - Java runtime: OpenJDK 64-Bit Server VM v11.0.14.1+1
18:03:29.590 INFO  VariantFiltration - Start Date/Time: August 26, 2025 at 6:03:29 PM CEST
18:03:29.591 INFO  VariantFiltration - ------------------------------------------------------------
18:03:29.591 INFO  VariantFiltration - ------------------------------------------------------------
18:03:29.591 INFO  VariantFiltration - HTSJDK Version: 2.21.2
18:03:29.591 INFO  VariantFiltration - Picard Version: 2.21.9
18:03:29.591 INFO  VariantFiltration - HTSJDK Defaults.COMPRESSION_LEVEL : 2
18:03:29.591 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
18:03:29.591 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
18:03:29.592 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
18:03:29.592 INFO  VariantFiltration - Deflater: IntelDeflater
18:03:29.592 INFO  VariantFiltration - Inflater: IntelInflater
18:03:29.592 INFO  VariantFiltration - GCS max retries/reopens: 20
18:03:29.592 INFO  VariantFiltration - Requester pays: disabled
18:03:29.592 INFO  VariantFiltration - Initializing engine
18:03:29.752 INFO  FeatureManager - Using codec VCFCodec to read file file:///storage/pruhonice1-ibot/shared/hieracium/pate/test_files/genotypeOutput/UFG_393202_P004_WA01/UFG_393202_P004_WA01.ab.vcf
18:03:29.798 INFO  VariantFiltration - Done initializing engine
18:03:29.856 INFO  ProgressMeter - Starting traversal
18:03:29.856 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
18:03:29.873 WARN  JexlEngine - ![0,10]: 'AF < 0.025;' < error
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.250])
        at org.apache.commons.jexl2.JexlArithmetic.toDouble(JexlArithmetic.java:1023) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.JexlArithmetic.compare(JexlArithmetic.java:699) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.JexlArithmetic.lessThan(JexlArithmetic.java:774) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:967) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.parser.ASTLTNode.jjtAccept(ASTLTNode.java:18) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.Interpreter.interpret(Interpreter.java:232) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.apache.commons.jexl2.ExpressionImpl.evaluate(ExpressionImpl.java:65) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at htsjdk.variant.variantcontext.JEXLMap.evaluateExpression(JEXLMap.java:186) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at htsjdk.variant.variantcontext.JEXLMap.get(JEXLMap.java:95) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at htsjdk.variant.variantcontext.JEXLMap.get(JEXLMap.java:15) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at htsjdk.variant.variantcontext.VariantContextUtils.match(VariantContextUtils.java:338) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.matchesFilter(VariantFiltration.java:427) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.filter(VariantFiltration.java:381) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.apply(VariantFiltration.java:340) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104) ~[gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) [?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) [?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) [?:?]
        at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102) [gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048) [gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139) [gatk-package-4.1.6.0-local.jar:4.1.6.0]
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191) [gatk-package-4.1.6.0-local.jar:4.1.6.0]

```

In `PATE.ctl` I have:

```
GATK_FILTER_EXPRESSION = "QD < 2.0" "QD_lt2"
GATK_FILTER_EXPRESSION = "FS > 60.0" "FS_gt60"
GATK_FILTER_EXPRESSION = "MQ < 40.0" "MQ_lt40"
GATK_FILTER_EXPRESSION = "ReadPosRankSum < -8.0" "ReadPosRankSum_ltm8"
GATK_FILTER_EXPRESSION = "AF < 0.025" "AF_lt025"
GATK_FILTER_EXPRESSION = "AF > 0.975" "AF_gt975"
GATK_FILTER_EXPRESSION = "DP < 10" "DP_lt10"
```

And further I see

```
$ grep -m1 -E "AF=" UFG_393202_P004_WA01.ab.vcf
L1      11      .       A       G       716.13  .       AC=1;AF=0.250;AN=4;BaseQRankSum=-1.396;DP=58;FS=0.000;MLEAC=1;MLEAF=0.250;MQ=59.63;MQRankSum=-1.342;QD=12.35;ReadPosRankSum=5.763;SOR=0.255     GT:AD:AF:DP:GQ:PL       0/0/0/1:38,20:0.345:58:7:721,0,7,86,1542
```

In logs (`grep ... | sort -u`) I see messages like

```
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.167, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.333, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.167, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.333, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.333, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.333, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.500, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.667])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.167, 0.833])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.250])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.250, 0.250])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.250, 0.250, 0.250])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.250, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.250, 0.750])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.167, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.167, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.333, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.500, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.333, 0.667])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.500, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.500, 0.167, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.500, 0.250])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.500, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.500, 0.500])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.667, 0.167])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.667, 0.333])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.750, 0.250])
java.lang.ArithmeticException: Double coercion: java.util.ArrayList:([0.833, 0.167])
WARN  JexlEngine - ![0,10]: 'AF < 0.025;' < error
WARN  JexlEngine - ![0,10]: 'AF > 0.975;' > error
WARN  JexlEngine - ![0,14]: 'ReadPosRankSum < -8.0;' undefined variable ReadPosRankSum
```

And in VCF files I find

```
AC=1,1
AC=1,1,1
AC=1,1,1,1
AC=1,1,1,1,1
AC=1,1,2
AC=1,1,2,1
AC=1,1,3
AC=1,2
AC=1,2,1
AC=1,2,2
AC=1,2,3
AC=1,3
AC=1,3,1
AC=1,4
AC=1,5
AC=2,1
AC=2,1,1
AC=2,1,1,1
AC=2,1,2
AC=2,2
AC=2,2,1
AC=2,3
AC=2,3,1
AC=2,4
AC=3,1
AC=3,1,1
AC=3,2
AC=3,3
AC=4,1
AC=4,2
AC=5,1
AF=0.167,0.167
AF=0.167,0.167,0.167
AF=0.167,0.167,0.167,0.167
AF=0.167,0.167,0.167,0.167,0.167
AF=0.167,0.167,0.333
AF=0.167,0.167,0.333,0.167
AF=0.167,0.167,0.500
AF=0.167,0.333
AF=0.167,0.333,0.167
AF=0.167,0.333,0.333
AF=0.167,0.333,0.500
AF=0.167,0.500
AF=0.167,0.500,0.167
AF=0.167,0.667
AF=0.167,0.833
AF=0.250,0.250
AF=0.250,0.250,0.250
AF=0.250,0.250,0.250,0.250
AF=0.250,0.250,0.500
AF=0.250,0.500
AF=0.250,0.750
AF=0.333,0.167
AF=0.333,0.167,0.167
AF=0.333,0.167,0.167,0.167
AF=0.333,0.167,0.333
AF=0.333,0.333
AF=0.333,0.333,0.167
AF=0.333,0.500
AF=0.333,0.500,0.167
AF=0.333,0.667
AF=0.500,0.167
AF=0.500,0.167,0.167
AF=0.500,0.250
AF=0.500,0.333
AF=0.500,0.500
AF=0.667,0.167
AF=0.667,0.333
AF=0.750,0.250
AF=0.833,0.167
```

My SW versions (`template.sh`) are

```
module add picard/2.27.5-gcc-10.2.1-zpit36s
module add bwa/0.7.17
module add gatk/4.1.6.0
module add samtools/1.21-gcc-10.2.1-xlivywn
module add bamtools/2.5.2-gcc-10.2.1-4cbzn52
module add r/4.1.3-gcc-10.2.1-6xt26dl
```

Clearly the issue is that there are multiallelic SNPs, and GATK JEXL filter is unable to correctly handle arrays of values. I think I have everything set correctly. If You could advice, how to make it running, it'd be nice.

**Comment by yjk-bertrand** [comment]
Hi Andy and George,
Sorry for poking, but we would really want to apply PATE to our data.  Can you please have a look at the error log above and advise us on how to properly run your method.
Thanks !
Yann
